# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desk',
            field=models.CharField(default='white', max_length=255),
            preserve_default=False,
        ),
    ]
